ColWidths_connform.ListSessions<|||>1<|||>163,50,50,50,50,50,10
ColsVisible_connform.ListSessions<|||>1<|||>0,1,4,6
ColPositions_connform.ListSessions<|||>1<|||>0,1,2,3,4,5,6
ColSort_connform.ListSessions<|||>1<|||>0,1
MainWinOnMonitor<|||>3<|||>0
ColWidths_MainForm.ListDatabases<|||>1<|||>150,80,50,50,50,50,50,50,50,50,120
ColsVisible_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColPositions_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColSort_MainForm.ListDatabases<|||>1<|||>0,0
ColWidths_MainForm.ListVariables<|||>1<|||>160,200,428
ColsVisible_MainForm.ListVariables<|||>1<|||>0,1,2
ColPositions_MainForm.ListVariables<|||>1<|||>0,1,2
ColSort_MainForm.ListVariables<|||>1<|||>0,0
ColWidths_MainForm.ListStatus<|||>1<|||>160,428,100,100
ColsVisible_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColPositions_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColSort_MainForm.ListStatus<|||>1<|||>0,0
ColWidths_MainForm.ListProcesses<|||>1<|||>70,80,80,80,80,50,50,238
ColsVisible_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColPositions_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColSort_MainForm.ListProcesses<|||>1<|||>0,1
ColWidths_MainForm.ListCommandStats<|||>1<|||>120,100,100,100,368
ColsVisible_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColPositions_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColSort_MainForm.ListCommandStats<|||>1<|||>1,1
ColWidths_MainForm.ListTables<|||>1<|||>120,70,70,120,120,70,100,50,70,70,70,70,70,90,120,70,70,70,50
ColsVisible_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,18
ColPositions_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
ColSort_MainForm.ListTables<|||>1<|||>0,0
LastSessions<|||>1<|||>PlataformaC\fomentoeconomico
LastActiveSession<|||>1<|||>PlataformaC\fomentoeconomico
FileDialogEncoding_MainForm<|||>3<|||>0
CreateDbCollation<|||>1<|||>latin1_swedish_ci
MainWinLeft<|||>3<|||>161
MainWinTop<|||>3<|||>113
SessionManager_WindowLeft<|||>3<|||>118
SessionManager_WindowTop<|||>3<|||>183
MemoEditorWidth<|||>3<|||>338
ColWidths_frmTableEditor.listColumns<|||>1<|||>38,100,154,90,60,138,120,117,130,140,100,100
ColsVisible_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColPositions_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColSort_frmTableEditor.listColumns<|||>1<|||>-1,0
ColWidths_frmTableEditor.treeIndexes<|||>1<|||>434,100,80
ColsVisible_frmTableEditor.treeIndexes<|||>1<|||>0,1,2
ColPositions_frmTableEditor.treeIndexes<|||>1<|||>0,1,2
ColSort_frmTableEditor.treeIndexes<|||>1<|||>-1,0
ColWidths_frmTableEditor.listForeignKeys<|||>1<|||>200,80,100,80,80,80
ColsVisible_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColPositions_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColSort_frmTableEditor.listForeignKeys<|||>1<|||>-1,0
ColWidths_frmTableEditor.listCheckConstraints<|||>1<|||>200,420
ColsVisible_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColPositions_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColSort_frmTableEditor.listCheckConstraints<|||>1<|||>-1,0
dbtreewidth<|||>3<|||>210
GroupTreeObjects<|||>3<|||>1
sqloutheight<|||>3<|||>252
MainWinWidth<|||>3<|||>974
MainWinHeight<|||>3<|||>1047
querymemoheight<|||>3<|||>396
MainWinMaximized<|||>3<|||>1
SQLFile0<|||>1<|||>C:\Users\Equipo3020\Downloads\informacion.sql
Servers\informacion\SessionCreated<|||>1<|||>2022-05-18 14:25:59
Servers\informacion\Host<|||>1<|||>127.0.0.1
Servers\informacion\WindowsAuth<|||>3<|||>0
Servers\informacion\CleartextPluginEnabled<|||>3<|||>0
Servers\informacion\User<|||>1<|||>root
Servers\informacion\Password<|||>1<|||>3
Servers\informacion\LoginPrompt<|||>3<|||>0
Servers\informacion\Port<|||>1<|||>3306
Servers\informacion\NetType<|||>3<|||>0
Servers\informacion\Compressed<|||>3<|||>0
Servers\informacion\LocalTimeZone<|||>3<|||>0
Servers\informacion\QueryTimeout<|||>3<|||>30
Servers\informacion\KeepAlive<|||>3<|||>20
Servers\informacion\FullTableStatus<|||>3<|||>1
Servers\informacion\Databases<|||>1<|||>
Servers\informacion\Library<|||>1<|||>libmariadb.dll
Servers\informacion\Comment<|||>1<|||>
Servers\informacion\StartupScriptFilename<|||>1<|||>
Servers\informacion\TreeBackground<|||>3<|||>536870911
Servers\informacion\SSHtunnelHost<|||>1<|||>
Servers\informacion\SSHtunnelHostPort<|||>3<|||>22
Servers\informacion\SSHtunnelUser<|||>1<|||>
Servers\informacion\SSHtunnelPassword<|||>1<|||>3
Servers\informacion\SSHtunnelTimeout<|||>3<|||>4
Servers\informacion\SSHtunnelPrivateKey<|||>1<|||>
Servers\informacion\SSHtunnelPort<|||>3<|||>3307
Servers\informacion\SSL_Active<|||>3<|||>0
Servers\informacion\SSL_Key<|||>1<|||>
Servers\informacion\SSL_Cert<|||>1<|||>
Servers\informacion\SSL_CA<|||>1<|||>
Servers\informacion\SSL_Cipher<|||>1<|||>
Servers\informacion\IgnoreDatabasePattern<|||>1<|||>
Servers\informacion\ServerVersionFull<|||>1<|||>5.7.33 - MySQL Community Server (GPL)
Servers\informacion\ConnectCount<|||>3<|||>4
Servers\informacion\ServerVersion<|||>3<|||>50733
Servers\informacion\LastConnect<|||>1<|||>2022-05-24 08:49:48
Servers\informacion\lastUsedDB<|||>1<|||>informacion
Servers\PlataformaC\SessionCreated<|||>1<|||>2022-05-25 08:57:43
Servers\PlataformaC\Folder<|||>3<|||>1
Servers\PlataformaC\fomentoeconomico\SessionCreated<|||>1<|||>2022-05-25 08:58:15
Servers\PlataformaC\fomentoeconomico\Host<|||>1<|||>127.0.0.1
Servers\PlataformaC\fomentoeconomico\WindowsAuth<|||>3<|||>0
Servers\PlataformaC\fomentoeconomico\CleartextPluginEnabled<|||>3<|||>0
Servers\PlataformaC\fomentoeconomico\User<|||>1<|||>root
Servers\PlataformaC\fomentoeconomico\Password<|||>1<|||>3
Servers\PlataformaC\fomentoeconomico\LoginPrompt<|||>3<|||>0
Servers\PlataformaC\fomentoeconomico\Port<|||>1<|||>3306
Servers\PlataformaC\fomentoeconomico\NetType<|||>3<|||>0
Servers\PlataformaC\fomentoeconomico\Compressed<|||>3<|||>0
Servers\PlataformaC\fomentoeconomico\LocalTimeZone<|||>3<|||>0
Servers\PlataformaC\fomentoeconomico\QueryTimeout<|||>3<|||>30
Servers\PlataformaC\fomentoeconomico\KeepAlive<|||>3<|||>20
Servers\PlataformaC\fomentoeconomico\FullTableStatus<|||>3<|||>1
Servers\PlataformaC\fomentoeconomico\Databases<|||>1<|||>
Servers\PlataformaC\fomentoeconomico\Library<|||>1<|||>libmariadb.dll
Servers\PlataformaC\fomentoeconomico\Comment<|||>1<|||>
Servers\PlataformaC\fomentoeconomico\StartupScriptFilename<|||>1<|||>
Servers\PlataformaC\fomentoeconomico\TreeBackground<|||>3<|||>536870911
Servers\PlataformaC\fomentoeconomico\SSHtunnelHost<|||>1<|||>
Servers\PlataformaC\fomentoeconomico\SSHtunnelHostPort<|||>3<|||>22
Servers\PlataformaC\fomentoeconomico\SSHtunnelUser<|||>1<|||>
Servers\PlataformaC\fomentoeconomico\SSHtunnelPassword<|||>1<|||>8
Servers\PlataformaC\fomentoeconomico\SSHtunnelTimeout<|||>3<|||>4
Servers\PlataformaC\fomentoeconomico\SSHtunnelPrivateKey<|||>1<|||>
Servers\PlataformaC\fomentoeconomico\SSHtunnelPort<|||>3<|||>3307
Servers\PlataformaC\fomentoeconomico\SSL_Active<|||>3<|||>0
Servers\PlataformaC\fomentoeconomico\SSL_Key<|||>1<|||>
Servers\PlataformaC\fomentoeconomico\SSL_Cert<|||>1<|||>
Servers\PlataformaC\fomentoeconomico\SSL_CA<|||>1<|||>
Servers\PlataformaC\fomentoeconomico\SSL_Cipher<|||>1<|||>
Servers\PlataformaC\fomentoeconomico\IgnoreDatabasePattern<|||>1<|||>
Servers\PlataformaC\fomentoeconomico\ServerVersionFull<|||>1<|||>5.7.33 - MySQL Community Server (GPL)
Servers\PlataformaC\fomentoeconomico\ConnectCount<|||>3<|||>1
Servers\PlataformaC\fomentoeconomico\ServerVersion<|||>3<|||>50733
Servers\PlataformaC\fomentoeconomico\LastConnect<|||>1<|||>2022-05-25 08:58:43
